/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SyncImport } from './routes/sync'
import { Route as SuccessImport } from './routes/success'
import { Route as SignupImport } from './routes/signup'
import { Route as SigninImport } from './routes/signin'
import { Route as SheetImport } from './routes/sheet'
import { Route as SampleImport } from './routes/sample'
import { Route as ProfileImport } from './routes/profile'
import { Route as PremiumImport } from './routes/premium'
import { Route as LogoutImport } from './routes/logout'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as AddproblemImport } from './routes/addproblem'
import { Route as IndexImport } from './routes/index'
import { Route as VerifyIdImport } from './routes/verify.$id'
import { Route as UpdateproblemIdImport } from './routes/updateproblem.$Id'
import { Route as ProblemIdImport } from './routes/problem.$Id'

// Create/Update Routes

const SyncRoute = SyncImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRoute,
} as any)

const SuccessRoute = SuccessImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SigninRoute = SigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const SheetRoute = SheetImport.update({
  id: '/sheet',
  path: '/sheet',
  getParentRoute: () => rootRoute,
} as any)

const SampleRoute = SampleImport.update({
  id: '/sample',
  path: '/sample',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const PremiumRoute = PremiumImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRoute,
} as any)

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AddproblemRoute = AddproblemImport.update({
  id: '/addproblem',
  path: '/addproblem',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VerifyIdRoute = VerifyIdImport.update({
  id: '/verify/$id',
  path: '/verify/$id',
  getParentRoute: () => rootRoute,
} as any)

const UpdateproblemIdRoute = UpdateproblemIdImport.update({
  id: '/updateproblem/$Id',
  path: '/updateproblem/$Id',
  getParentRoute: () => rootRoute,
} as any)

const ProblemIdRoute = ProblemIdImport.update({
  id: '/problem/$Id',
  path: '/problem/$Id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/addproblem': {
      id: '/addproblem'
      path: '/addproblem'
      fullPath: '/addproblem'
      preLoaderRoute: typeof AddproblemImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/sample': {
      id: '/sample'
      path: '/sample'
      fullPath: '/sample'
      preLoaderRoute: typeof SampleImport
      parentRoute: typeof rootRoute
    }
    '/sheet': {
      id: '/sheet'
      path: '/sheet'
      fullPath: '/sheet'
      preLoaderRoute: typeof SheetImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessImport
      parentRoute: typeof rootRoute
    }
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncImport
      parentRoute: typeof rootRoute
    }
    '/problem/$Id': {
      id: '/problem/$Id'
      path: '/problem/$Id'
      fullPath: '/problem/$Id'
      preLoaderRoute: typeof ProblemIdImport
      parentRoute: typeof rootRoute
    }
    '/updateproblem/$Id': {
      id: '/updateproblem/$Id'
      path: '/updateproblem/$Id'
      fullPath: '/updateproblem/$Id'
      preLoaderRoute: typeof UpdateproblemIdImport
      parentRoute: typeof rootRoute
    }
    '/verify/$id': {
      id: '/verify/$id'
      path: '/verify/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof VerifyIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addproblem': typeof AddproblemRoute
  '/dashboard': typeof DashboardRoute
  '/logout': typeof LogoutRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/sample': typeof SampleRoute
  '/sheet': typeof SheetRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/success': typeof SuccessRoute
  '/sync': typeof SyncRoute
  '/problem/$Id': typeof ProblemIdRoute
  '/updateproblem/$Id': typeof UpdateproblemIdRoute
  '/verify/$id': typeof VerifyIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addproblem': typeof AddproblemRoute
  '/dashboard': typeof DashboardRoute
  '/logout': typeof LogoutRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/sample': typeof SampleRoute
  '/sheet': typeof SheetRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/success': typeof SuccessRoute
  '/sync': typeof SyncRoute
  '/problem/$Id': typeof ProblemIdRoute
  '/updateproblem/$Id': typeof UpdateproblemIdRoute
  '/verify/$id': typeof VerifyIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/addproblem': typeof AddproblemRoute
  '/dashboard': typeof DashboardRoute
  '/logout': typeof LogoutRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/sample': typeof SampleRoute
  '/sheet': typeof SheetRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/success': typeof SuccessRoute
  '/sync': typeof SyncRoute
  '/problem/$Id': typeof ProblemIdRoute
  '/updateproblem/$Id': typeof UpdateproblemIdRoute
  '/verify/$id': typeof VerifyIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addproblem'
    | '/dashboard'
    | '/logout'
    | '/premium'
    | '/profile'
    | '/sample'
    | '/sheet'
    | '/signin'
    | '/signup'
    | '/success'
    | '/sync'
    | '/problem/$Id'
    | '/updateproblem/$Id'
    | '/verify/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addproblem'
    | '/dashboard'
    | '/logout'
    | '/premium'
    | '/profile'
    | '/sample'
    | '/sheet'
    | '/signin'
    | '/signup'
    | '/success'
    | '/sync'
    | '/problem/$Id'
    | '/updateproblem/$Id'
    | '/verify/$id'
  id:
    | '__root__'
    | '/'
    | '/addproblem'
    | '/dashboard'
    | '/logout'
    | '/premium'
    | '/profile'
    | '/sample'
    | '/sheet'
    | '/signin'
    | '/signup'
    | '/success'
    | '/sync'
    | '/problem/$Id'
    | '/updateproblem/$Id'
    | '/verify/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddproblemRoute: typeof AddproblemRoute
  DashboardRoute: typeof DashboardRoute
  LogoutRoute: typeof LogoutRoute
  PremiumRoute: typeof PremiumRoute
  ProfileRoute: typeof ProfileRoute
  SampleRoute: typeof SampleRoute
  SheetRoute: typeof SheetRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SuccessRoute: typeof SuccessRoute
  SyncRoute: typeof SyncRoute
  ProblemIdRoute: typeof ProblemIdRoute
  UpdateproblemIdRoute: typeof UpdateproblemIdRoute
  VerifyIdRoute: typeof VerifyIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddproblemRoute: AddproblemRoute,
  DashboardRoute: DashboardRoute,
  LogoutRoute: LogoutRoute,
  PremiumRoute: PremiumRoute,
  ProfileRoute: ProfileRoute,
  SampleRoute: SampleRoute,
  SheetRoute: SheetRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SuccessRoute: SuccessRoute,
  SyncRoute: SyncRoute,
  ProblemIdRoute: ProblemIdRoute,
  UpdateproblemIdRoute: UpdateproblemIdRoute,
  VerifyIdRoute: VerifyIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/addproblem",
        "/dashboard",
        "/logout",
        "/premium",
        "/profile",
        "/sample",
        "/sheet",
        "/signin",
        "/signup",
        "/success",
        "/sync",
        "/problem/$Id",
        "/updateproblem/$Id",
        "/verify/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/addproblem": {
      "filePath": "addproblem.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/premium": {
      "filePath": "premium.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/sample": {
      "filePath": "sample.tsx"
    },
    "/sheet": {
      "filePath": "sheet.tsx"
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/success": {
      "filePath": "success.tsx"
    },
    "/sync": {
      "filePath": "sync.tsx"
    },
    "/problem/$Id": {
      "filePath": "problem.$Id.tsx"
    },
    "/updateproblem/$Id": {
      "filePath": "updateproblem.$Id.tsx"
    },
    "/verify/$id": {
      "filePath": "verify.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
