/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SinginImport } from './routes/singin'
import { Route as SignupImport } from './routes/signup'
import { Route as SampleImport } from './routes/sample'
import { Route as LogoutImport } from './routes/logout'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as AddproblemImport } from './routes/addproblem'
import { Route as IndexImport } from './routes/index'
import { Route as ProblemIdImport } from './routes/problem.$Id'

// Create/Update Routes

const SinginRoute = SinginImport.update({
  id: '/singin',
  path: '/singin',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SampleRoute = SampleImport.update({
  id: '/sample',
  path: '/sample',
  getParentRoute: () => rootRoute,
} as any)

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AddproblemRoute = AddproblemImport.update({
  id: '/addproblem',
  path: '/addproblem',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProblemIdRoute = ProblemIdImport.update({
  id: '/problem/$Id',
  path: '/problem/$Id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/addproblem': {
      id: '/addproblem'
      path: '/addproblem'
      fullPath: '/addproblem'
      preLoaderRoute: typeof AddproblemImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/sample': {
      id: '/sample'
      path: '/sample'
      fullPath: '/sample'
      preLoaderRoute: typeof SampleImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/singin': {
      id: '/singin'
      path: '/singin'
      fullPath: '/singin'
      preLoaderRoute: typeof SinginImport
      parentRoute: typeof rootRoute
    }
    '/problem/$Id': {
      id: '/problem/$Id'
      path: '/problem/$Id'
      fullPath: '/problem/$Id'
      preLoaderRoute: typeof ProblemIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addproblem': typeof AddproblemRoute
  '/dashboard': typeof DashboardRoute
  '/logout': typeof LogoutRoute
  '/sample': typeof SampleRoute
  '/signup': typeof SignupRoute
  '/singin': typeof SinginRoute
  '/problem/$Id': typeof ProblemIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addproblem': typeof AddproblemRoute
  '/dashboard': typeof DashboardRoute
  '/logout': typeof LogoutRoute
  '/sample': typeof SampleRoute
  '/signup': typeof SignupRoute
  '/singin': typeof SinginRoute
  '/problem/$Id': typeof ProblemIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/addproblem': typeof AddproblemRoute
  '/dashboard': typeof DashboardRoute
  '/logout': typeof LogoutRoute
  '/sample': typeof SampleRoute
  '/signup': typeof SignupRoute
  '/singin': typeof SinginRoute
  '/problem/$Id': typeof ProblemIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addproblem'
    | '/dashboard'
    | '/logout'
    | '/sample'
    | '/signup'
    | '/singin'
    | '/problem/$Id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addproblem'
    | '/dashboard'
    | '/logout'
    | '/sample'
    | '/signup'
    | '/singin'
    | '/problem/$Id'
  id:
    | '__root__'
    | '/'
    | '/addproblem'
    | '/dashboard'
    | '/logout'
    | '/sample'
    | '/signup'
    | '/singin'
    | '/problem/$Id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddproblemRoute: typeof AddproblemRoute
  DashboardRoute: typeof DashboardRoute
  LogoutRoute: typeof LogoutRoute
  SampleRoute: typeof SampleRoute
  SignupRoute: typeof SignupRoute
  SinginRoute: typeof SinginRoute
  ProblemIdRoute: typeof ProblemIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddproblemRoute: AddproblemRoute,
  DashboardRoute: DashboardRoute,
  LogoutRoute: LogoutRoute,
  SampleRoute: SampleRoute,
  SignupRoute: SignupRoute,
  SinginRoute: SinginRoute,
  ProblemIdRoute: ProblemIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/addproblem",
        "/dashboard",
        "/logout",
        "/sample",
        "/signup",
        "/singin",
        "/problem/$Id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/addproblem": {
      "filePath": "addproblem.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/sample": {
      "filePath": "sample.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/singin": {
      "filePath": "singin.tsx"
    },
    "/problem/$Id": {
      "filePath": "problem.$Id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
